### ISSUE TITLE
ctf viewer error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-tomo#235]
Quite difficult to reproduce, but seem to happen quite often for me:

```
Exception in Tkinter callback
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/scipion3-public-dev/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
return self.func(*args)
File "/net/nfs1/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-tomo/tomo/viewers/views_tkinter_tree.py", line 1092, in _createPloter
self.plotterParentItem(itemSelected)
File "/net/nfs1/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-tomo/tomo/viewers/views_tkinter_tree.py", line 1035, in plotterParentItem
angList.append(int(ts[index].getTiltAngle()))
File "/net/nfs1/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/object.py", line 1125, in __getitem__
item = self._getMapper().selectById(itemId)
File "/net/nfs1/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 826, in selectById
objRow = self.db.selectObjectById(objId)
File "/net/nfs1/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 1255, in selectObjectById
self.executeCommand(self.selectCmd(ID + "=?"), (objId,))
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

Anyone seen this?

**Comment by azazellochg** [comment]
might have been fixed with https://github.com/scipion-em/scipion-em-tomo/pull/251
