### ISSUE TITLE
scipion test tomo.tests.test_tomo_base failed

### ISSUE THREAD

**Issue by davidhoover** [scipion-em/scipion-em-tomo#246]
*************** last 50 lines of STD ERR *********************

Traceback (most recent call last):
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/xmipp2/protocols/protocol_mltomo.py", line 117, in runMLTomo
    self._createFilesForMLTomo()
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/xmipp2/protocols/protocol_mltomo.py", line 213, in _createFilesForMLTomo
    if inputVols.getFirstItem().getTransform() is None:
  File "/usr/local/apps/scipion/3.0.11/scipion-em-tomo/tomo/objects.py", line 1502, in getTransform
    matrix = self._transform.getMatrix()
AttributeError: 'NoneType' object has no attribute 'getMatrix'
Protocol failed: 'NoneType' object has no attribute 'getMatrix'

*************** end of STD ERR *********************

[   FAILED ] TestTomoAssignAlignment.test_assignAlignment

Traceback (most recent call last):
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/local/apps/scipion/3.0.11/scipion-em-tomo/tomo/tests/test_tomo_base.py", line 673, in test_assignAlignment
    assign = self._assignAlignment()
  File "/usr/local/apps/scipion/3.0.11/scipion-em-tomo/tomo/tests/test_tomo_base.py", line 663, in _assignAlignment
    protImport2, protMltomo = self._runPreviousProtocols()
  File "/usr/local/apps/scipion/3.0.11/scipion-em-tomo/tomo/tests/test_tomo_base.py", line 655, in _runPreviousProtocols
    self.launchProtocol(protMltomo)
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol xmipp2 - mltomo execution failed. See last log lines above for more details.

**Comment by azazellochg** [comment]
xmipp2??? oh my, I dont even know who supports that today. @pconesa, any clue ?

**Comment by pconesa** [comment]
I've asked xmipp team. Let's see

**Comment by pconesa** [comment]
SInce is a test, we may remove it if no one takes care of it.
