### ISSUE TITLE
Error if tilt series filename contains a '-' character or begins by a numerical character

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-tomo#46]
Concretely, file used was **64K_defocus-2_tomo_10_bin1_ali_bin1**
And the usage can be observed in the following image:
![image](https://user-images.githubusercontent.com/54907551/81582147-f78d1680-93af-11ea-9d52-b83bacce5ed8.png)

Debugging myself I could reach that the problem appears when writing in the sqlite.
Scipion stdout was:
File 'Runs/001509_ProtImportTs/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:        HostName: jjimenez-G3-3579
00003:             PID: 10389
00004:      pyworkflow: 3.0.0a7
00005:      currentDir: /home/jjimenez/ScipionUserData/projects/jtest
00006:      workingDir: Runs/001509_ProtImportTs
00007:         runMode: Continue
00008:             MPI: 1
00009:         threads: 1
00010:   len(steps) 1 len(prevSteps) 0 
00011:    Starting at step: 1
00012:    Running steps 
00013:   STARTED: importStep, step 1
00014:     2020-05-11 17:43:29.547801
00015:   Using glob pattern: '/home/jjimenez/Documents/relion/*_bin1_ali_bin1.mrc'
00016:   Using regex pattern: '/home/jjimenez/Documents/relion/(?P<TS>.*)_bin1_ali_bin1.mrc'
00017:   Traceback (most recent call last):
00018:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
00019:       self._run()
00020:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
00021:       resultFiles = self._runFunc()
00022:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
00023:       return self._func(*self._args)
00024:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-em-tomo/tomo/protocols/protocol_ts_import.py", line 243, in importStep
00025:       tiltAngle=ta))
00026:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-em-tomo/tomo/objects.py", line 114, in append
00027:       data.SetOfImages.append(self, tiltImage)
00028:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-em/pwem/objects/data.py", line 1030, in append
00029:       EMSet.append(self, image)
00030:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/object.py", line 1233, in append
00031:       self._insertItem(item)
00032:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/object.py", line 1237, in _insertItem
00033:       self._getMapper().insert(item)
00034:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 764, in insert
00035:       self.db.createTables(obj.getObjDict(includeClass=True))
00036:     File "/home/jjimenez/Jorge/Sync/scipion3/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 1114, in createTables
00037:       )""" % self.tablePrefix)
00038:   sqlite3.OperationalError: unrecognized token: "64K_defocus"
00039:   Protocol failed: unrecognized token: "64K_defocus"
00040:   FAILED: importStep, step 1
00041:     2020-05-11 17:43:32.602951
00042:   *** Last status is failed 
00043:   ------------------- PROTOCOL FAILED (DONE 1/1)

**Comment by JorMaister** [comment]
If the name of a tilt-series begins by a numeric character, it also fails. The error below corresponds to a TS named 20191216_SBKR3_tomo_Defocus_3_1_tomo_12_bin1_ali.mrc. 

File 'Runs/000696_ProtImportTs/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:        HostName: einstein-dos
00003:             PID: 25055
00004:      pyworkflow: 3.0.0a11
00005:      currentDir: /home/rmelero/ScipionUserData/projects/testJJ
00006:      workingDir: Runs/000696_ProtImportTs
00007:         runMode: Continue
00008:             MPI: 1
00009:         threads: 1
00010:   len(steps) 1 len(prevSteps) 0 
00011:    Starting at step: 1
00012:    Running steps 
00013:   STARTED: importStep, step 1
00014:     2020-07-02 10:51:59.297035
00015:   Using glob pattern: '/home/rmelero/MAYR/ERC/TEST_Scipion/exJJ/20191216_SKBR3_tomo_Defocus_3_1_tomo_12_bin1_ali.mrc'
00016:   Using regex pattern: '/home/rmelero/MAYR/ERC/TEST_Scipion/exJJ/20191216_SKBR3_tomo_Defocus_3_1_tomo_12_bin1_ali.mrc'
00017:   Traceback (most recent call last):
00018:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
00019:       self._run()
00020:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
00021:       resultFiles = self._runFunc()
00022:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
00023:       return self._func(*self._args)
00024:     File "/home/rmelero/scipion3_jj_installation/scipion-em-tomo/tomo/protocols/protocol_ts_import.py", line 229, in importStep
00025:       tiltAngle=ta))
00026:     File "/home/rmelero/scipion3_jj_installation/scipion-em-tomo/tomo/objects.py", line 115, in append
00027:       data.SetOfImages.append(self, tiltImage)
00028:     File "/home/rmelero/scipion3_jj_installation/scipion-em/pwem/objects/data.py", line 1027, in append
00029:       EMSet.append(self, image)
00030:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/object.py", line 1233, in append
00031:       self._insertItem(item)
00032:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/object.py", line 1237, in _insertItem
00033:       self._getMapper().insert(item)
00034:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 764, in insert
00035:       self.db.createTables(obj.getObjDict(includeClass=True))
00036:     File "/home/rmelero/scipion3_jj_installation/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 1114, in createTables
00037:       )""" % self.tablePrefix)
00038:   sqlite3.OperationalError: unrecognized token: "20191216_SKBR3_tomo_Defocus_3_1_tomo_12_bin1_ali_Classes"
00039:   Protocol failed: unrecognized token: "20191216_SKBR3_tomo_Defocus_3_1_tomo_12_bin1_ali_Classes"
00040:   FAILED: importStep, step 1
00041:     2020-07-02 10:52:02.911810
00042:   *** Last status is failed 
00043:   ------------------- PROTOCOL FAILED (DONE 1/1)

It seems to be a database writing error. It the tilt series file is renamed to, e. g.,  SKBR3_tomo_20191216_Defocus_3_1_tomo_12_bin1_ali.mrc, it works correctly.
