### ISSUE TITLE
tilt series viewer errors

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-tomo#488]
on a set of TS movies:

1)
```
Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/tree.py", line 326, in _onSelect
    self.itemClick(obj)
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/dialog.py", line 657, in _itemClick
    self.previewCallBack(obj, self.previewFrame)
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/viewers/views_tkinter_tree.py", line 425, in previewTiltSeries
    preview._update(data)
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/matplotlib_image.py", line 125, in _update
    self.figureimg.set_data(Z)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/image.py", line 710, in set_data
    raise TypeError("Invalid shape {} for image data"
TypeError: Invalid shape (8, 1, 7676, 7420) for image data
```

2)
```
Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/tree.py", line 326, in _onSelect
    self.itemClick(obj)
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/dialog.py", line 657, in _itemClick
    self.previewCallBack(obj, self.previewFrame)
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/viewers/views_tkinter_tree.py", line 421, in previewTiltSeries
    text = "Tilt image at %sº" % obj.getTiltAngle()
AttributeError: 'TiltSeriesM' object has no attribute 'getTiltAngle'
```

**Comment by azazellochg** [comment]
I think we should not show any previews for movies.

**Comment by fonsecareyna82** [comment]
It doesn't make sense to visualize them, right? However, I have already made some changes to avoid errors when opening the TiltSeriesM.
